### ISSUE TITLE
[BUG] List of Systems do not get updated after Tableau sync

### ISSUE THREAD

**Issue by ealtuna** [GoogleCloudPlatform/datacatalog-connectors-bi#49] opened 2020-12-07 17:03 UTC
**What happened**:

I used the connector to sync data from a Tableau server to Google Data Catalog. The data came in fine, but the list of systems in Data Catalog does not get updated to include Tableau, even after days. Honestly, most likely this is an issue with Catalog itself and not the connector, and it's maybe even expected behavior.

**What you expected to happen**:

List of systems should include Tableau

**How to reproduce it (as minimally and precisely as possible)**:

Sync a Tableau server to Data Catalog, look in Google Data Catalog, main dashboard, list for systems.

**Anything else we need to know?**:

Including image with the result:

![image](https://user-images.githubusercontent.com/11414127/101380981-3458b780-3884-11eb-9865-c5d2928bb83e.png)

**Comment by ricardolsmendes** [comment] 2020-12-07 19:00
Thanks for filing this issue, @ealtuna.
As you've already mentioned, this is not a connector issue and looks like Data Catalog's intended behavior: user-specified systems are not listed in the UI for now. Anyway, you can search for Tableau assets by using the `system=tableau` facet, and I also suggest you file a feature request in the [Google Issue Tracker](https://issuetracker.google.com/savedsearches/5487242), so the Data Catalog product team will be aware of it.

I'm closing the issue, please reopen it if we can help with anything else.

Kind regards,

**Closed by ricardolsmendes** 2020-12-07 19:00 UTC
Labels: bug

**Comment by ealtuna** [comment] 2020-12-07 20:13
Thank you for your fast response. I am adding the link to [Google Issue Tracker](https://issuetracker.google.com/issues/175043877) as reference for users facing same situation in the future.
